#!/bin/sh

ngx_addon_name=ngx_http_mruby_module
mruby_root=$ngx_addon_dir/mruby

HTTP_FILTER_MODULES="$HTTP_FILTER_MODULES ngx_http_mruby_module"

NGX_ADDON_SRCS="$NGX_ADDON_SRCS \
                $ngx_addon_dir/src/ngx_http_mruby_module.c \
                $ngx_addon_dir/src/ngx_http_mruby_core.c \
                $ngx_addon_dir/src/ngx_http_mruby_init.c \
                $ngx_addon_dir/src/ngx_http_mruby_request.c \
                $ngx_addon_dir/src/ngx_http_mruby_handler.c \
                $ngx_addon_dir/src/ngx_http_mruby_filter_handler.c \
                $ngx_addon_dir/src/ngx_http_mruby_state.c \
                $ngx_addon_dir/src/ngx_http_mruby_directive.c \
                $ngx_addon_dir/src/ngx_http_mruby_var.c \
                $ngx_addon_dir/src/ngx_http_mruby_error.c \
                $ngx_addon_dir/src/ngx_http_mruby_connection.c \
                $ngx_addon_dir/src/ngx_http_mruby_server.c \
                $ngx_addon_dir/src/ngx_http_mruby_context.c \
                $ngx_addon_dir/src/ngx_http_mruby_digest.c \
                $ngx_addon_dir/src/ngx_http_mruby_time.c \
                $ngx_addon_dir/src/ngx_http_mruby_base64.c \
                "

CORE_LIBS="$CORE_LIBS $mruby_root/build/host/mrblib/mrblib.o $mruby_root/build/host/lib/libmruby.a"
CORE_INCS="$CORE_INCS $mruby_root/src $mruby_root/include"
cp $mruby_root/build/host/lib/libmruby.flags.mak $ngx_addon_dir/libmruby.flags.mak

# original libmruby.flags.mak can not included
perl -i.bak -pe "s/^(MRUBY_CFLAGS) = (.*)$/\1=\"\2\"/"              $ngx_addon_dir/libmruby.flags.mak
perl -i.bak -pe "s/^(MRUBY_LDFLAGS) = (.*)$/\1=\"\2\"/"             $ngx_addon_dir/libmruby.flags.mak
perl -i.bak -pe "s/^(MRUBY_LDFLAGS_BEFORE_LIBS) = (.*)$/\1=\"\2\"/" $ngx_addon_dir/libmruby.flags.mak
perl -i.bak -pe "s/^(MRUBY_LIBS) = (.*)$/\1=\"\2\"/"                $ngx_addon_dir/libmruby.flags.mak

# drop the option for optimization in mruby(use nginx's)
perl -i.bak -pe "s/-O[0-9]? //" $ngx_addon_dir/libmruby.flags.mak

. $ngx_addon_dir/libmruby.flags.mak
CORE_LIBS="$CORE_LIBS $MRUBY_LIBS"
CFLAGS="$CFLAGS $MRUBY_CFLAGS "

# ngx_devel_kit
have=NDK_SET_VAR . auto/have
